FROM registry.redhat.io/ansible-automation-platform-26/ansible-dev-tools-rhel9:latest

ARG TARGETPLATFORM

ARG USERNAME=podman
ARG USERID=1000
ARG GROUPID=1000

ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN
ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_VALIDATED_TOKEN

ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub,automation_hub_validated,release_galaxy
ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL=https://console.redhat.com/api/automation-hub/content/published
ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_VALIDATED_URL=https://console.redhat.com/api/automation-hub/content/validated

ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_VALIDATED_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token

ENV ANSIBLE_GALAXY_SERVER_RELEASE_GALAXY_URL=https://galaxy.ansible.com

# the default container user is root, but HOME is set to /home/runner
# this confuses ansible, and me...
ENV ANSIBLE_ASYNC_DIR=/tmp/ansible_async

USER root

#
# Setup opencode
#
RUN curl -fsSL https://opencode.ai/install | bash

#
# Setup OC client
#
RUN if [ "$TARGETPLATFORM" = "linux/arm/v7" ]; then ARCHITECTURE=arm64; elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then ARCHITECTURE=arm64; else ARCHITECTURE=amd64; fi \
    && echo "targetplatform: $TARGETPLATFORM | architecture: $ARCHITECTURE" \
    && ( cd /tmp \
    && curl -fLO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-${ARCHITECTURE}-rhel9.tar.gz \
    && tar zxvf /tmp/openshift-client-linux-${ARCHITECTURE}-rhel9.tar.gz -C /usr/local/bin \
    && rm /tmp/openshift-client-linux-${ARCHITECTURE}-rhel9.tar.gz)

#
# Setup virtctl
#
RUN if [ "$TARGETPLATFORM" = "linux/arm/v7" ]; then ARCHITECTURE=arm64; elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then ARCHITECTURE=arm64; else ARCHITECTURE=amd64; fi \
    && echo "targetplatform: $TARGETPLATFORM | architecture: $ARCHITECTURE" \
    && ( cd /usr/local/bin \
    && export VERSION=$(curl https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt) \
    && curl -Lo virtctl https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/virtctl-${VERSION}-linux-${ARCHITECTURE} \
    && chmod 755 /usr/local/bin/virtctl)

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY requirements.yaml .
RUN ansible-galaxy collection install -v -p /usr/share/ansible/collections -r requirements.yaml

RUN microdnf install -y sudo findutils procps-ng && microdnf clean all
RUN usermod -aG wheel podman

# Allow wheel to perform sudo actions with no password
RUN sed -e 's/^%wheel/#%wheel/g' -e 's/^# %wheel/%wheel/g' -i /etc/sudoers

RUN mkdir /commandhistory \
    && touch /commandhistory/.bash_history \
    && chown -R $USERNAME /commandhistory \
    && echo "HISTFILE=/commandhistory/.zsh_history" >> "${HOME}/.zshrc"
