collections:

  - name: kubernetes.core
    version: 6.4.0
    source: https://console.redhat.com/api/automation-hub/content/published

  - name: ansible.controller
    version: 4.7.11
    source: https://console.redhat.com/api/automation-hub/content/published

  - name: ansible.platform
    version: 2.6.20260504
    source: https://console.redhat.com/api/automation-hub/content/published

  - name: ansible.hub
    version: 1.0.6
    source: https://console.redhat.com/api/automation-hub/content/published

  - name: ansible.eda
    version: 2.11.0
    source: https://console.redhat.com/api/automation-hub/content/published

  - name: infra.aap_configuration
    version: 4.4.0
    source: https://console.redhat.com/api/automation-hub/content/validated

  - name: infra.aap_utilities
    version: 3.1.0
    source: https://console.redhat.com/api/automation-hub/content/validated

  - name: infra.ah_configuration
    version: 2.1.0
    source: https://console.redhat.com/api/automation-hub/content/validated

  - name: community.general
    version: 12.6.0
    source: https://galaxy.ansible.com
